[project]
name = "smart-student-agent"
version = "0.1.0"
description = "AI study assistant using Gemini"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "openai-agents>=0.0.19",
    "python-dotenv>=1.0.0",
]
